/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as DevSessionRouteImport } from './routes/dev.session'
import { Route as AppValidadorRouteImport } from './routes/app.validador'
import { Route as AppPlanosRouteImport } from './routes/app.planos'
import { Route as AppPagamentosRouteImport } from './routes/app.pagamentos'
import { Route as AppPadroesRouteImport } from './routes/app.padroes'
import { Route as AppIaRouteImport } from './routes/app.ia'
import { Route as AppContaRouteImport } from './routes/app.conta'
import { Route as AppCalendarioRouteImport } from './routes/app.calendario'
import { Route as AppBancaRouteImport } from './routes/app.banca'
import { Route as AppAssinaturaRouteImport } from './routes/app.assinatura'
import { Route as AppAgentesRouteImport } from './routes/app.agentes'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppAdminUsersRouteImport } from './routes/app.admin.users'
import { Route as AppAdminModulesRouteImport } from './routes/app.admin.modules'
import { Route as AppAdminLogsRouteImport } from './routes/app.admin.logs'
import { Route as AppAdminCrmRouteImport } from './routes/app.admin.crm'
import { Route as AppAdminBroadcastRouteImport } from './routes/app.admin.broadcast'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const DevSessionRoute = DevSessionRouteImport.update({
  id: '/dev/session',
  path: '/dev/session',
  getParentRoute: () => rootRouteImport,
} as any)
const AppValidadorRoute = AppValidadorRouteImport.update({
  id: '/validador',
  path: '/validador',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanosRoute = AppPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AppRoute,
} as any)
const AppPagamentosRoute = AppPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AppRoute,
} as any)
const AppPadroesRoute = AppPadroesRouteImport.update({
  id: '/padroes',
  path: '/padroes',
  getParentRoute: () => AppRoute,
} as any)
const AppIaRoute = AppIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AppRoute,
} as any)
const AppContaRoute = AppContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarioRoute = AppCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AppRoute,
} as any)
const AppBancaRoute = AppBancaRouteImport.update({
  id: '/banca',
  path: '/banca',
  getParentRoute: () => AppRoute,
} as any)
const AppAssinaturaRoute = AppAssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentesRoute = AppAgentesRouteImport.update({
  id: '/agentes',
  path: '/agentes',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminModulesRoute = AppAdminModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminLogsRoute = AppAdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminCrmRoute = AppAdminCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminBroadcastRoute = AppAdminBroadcastRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/agentes': typeof AppAgentesRoute
  '/app/assinatura': typeof AppAssinaturaRoute
  '/app/banca': typeof AppBancaRoute
  '/app/calendario': typeof AppCalendarioRoute
  '/app/conta': typeof AppContaRoute
  '/app/ia': typeof AppIaRoute
  '/app/padroes': typeof AppPadroesRoute
  '/app/pagamentos': typeof AppPagamentosRoute
  '/app/planos': typeof AppPlanosRoute
  '/app/validador': typeof AppValidadorRoute
  '/dev/session': typeof DevSessionRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/broadcast': typeof AppAdminBroadcastRoute
  '/app/admin/crm': typeof AppAdminCrmRoute
  '/app/admin/logs': typeof AppAdminLogsRoute
  '/app/admin/modules': typeof AppAdminModulesRoute
  '/app/admin/users': typeof AppAdminUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/agentes': typeof AppAgentesRoute
  '/app/assinatura': typeof AppAssinaturaRoute
  '/app/banca': typeof AppBancaRoute
  '/app/calendario': typeof AppCalendarioRoute
  '/app/conta': typeof AppContaRoute
  '/app/ia': typeof AppIaRoute
  '/app/padroes': typeof AppPadroesRoute
  '/app/pagamentos': typeof AppPagamentosRoute
  '/app/planos': typeof AppPlanosRoute
  '/app/validador': typeof AppValidadorRoute
  '/dev/session': typeof DevSessionRoute
  '/app': typeof AppIndexRoute
  '/app/admin/broadcast': typeof AppAdminBroadcastRoute
  '/app/admin/crm': typeof AppAdminCrmRoute
  '/app/admin/logs': typeof AppAdminLogsRoute
  '/app/admin/modules': typeof AppAdminModulesRoute
  '/app/admin/users': typeof AppAdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/agentes': typeof AppAgentesRoute
  '/app/assinatura': typeof AppAssinaturaRoute
  '/app/banca': typeof AppBancaRoute
  '/app/calendario': typeof AppCalendarioRoute
  '/app/conta': typeof AppContaRoute
  '/app/ia': typeof AppIaRoute
  '/app/padroes': typeof AppPadroesRoute
  '/app/pagamentos': typeof AppPagamentosRoute
  '/app/planos': typeof AppPlanosRoute
  '/app/validador': typeof AppValidadorRoute
  '/dev/session': typeof DevSessionRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/broadcast': typeof AppAdminBroadcastRoute
  '/app/admin/crm': typeof AppAdminCrmRoute
  '/app/admin/logs': typeof AppAdminLogsRoute
  '/app/admin/modules': typeof AppAdminModulesRoute
  '/app/admin/users': typeof AppAdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/admin'
    | '/app/agentes'
    | '/app/assinatura'
    | '/app/banca'
    | '/app/calendario'
    | '/app/conta'
    | '/app/ia'
    | '/app/padroes'
    | '/app/pagamentos'
    | '/app/planos'
    | '/app/validador'
    | '/dev/session'
    | '/app/'
    | '/app/admin/broadcast'
    | '/app/admin/crm'
    | '/app/admin/logs'
    | '/app/admin/modules'
    | '/app/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/admin'
    | '/app/agentes'
    | '/app/assinatura'
    | '/app/banca'
    | '/app/calendario'
    | '/app/conta'
    | '/app/ia'
    | '/app/padroes'
    | '/app/pagamentos'
    | '/app/planos'
    | '/app/validador'
    | '/dev/session'
    | '/app'
    | '/app/admin/broadcast'
    | '/app/admin/crm'
    | '/app/admin/logs'
    | '/app/admin/modules'
    | '/app/admin/users'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/admin'
    | '/app/agentes'
    | '/app/assinatura'
    | '/app/banca'
    | '/app/calendario'
    | '/app/conta'
    | '/app/ia'
    | '/app/padroes'
    | '/app/pagamentos'
    | '/app/planos'
    | '/app/validador'
    | '/dev/session'
    | '/app/'
    | '/app/admin/broadcast'
    | '/app/admin/crm'
    | '/app/admin/logs'
    | '/app/admin/modules'
    | '/app/admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DevSessionRoute: typeof DevSessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/dev/session': {
      id: '/dev/session'
      path: '/dev/session'
      fullPath: '/dev/session'
      preLoaderRoute: typeof DevSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/validador': {
      id: '/app/validador'
      path: '/validador'
      fullPath: '/app/validador'
      preLoaderRoute: typeof AppValidadorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/planos': {
      id: '/app/planos'
      path: '/planos'
      fullPath: '/app/planos'
      preLoaderRoute: typeof AppPlanosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pagamentos': {
      id: '/app/pagamentos'
      path: '/pagamentos'
      fullPath: '/app/pagamentos'
      preLoaderRoute: typeof AppPagamentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/padroes': {
      id: '/app/padroes'
      path: '/padroes'
      fullPath: '/app/padroes'
      preLoaderRoute: typeof AppPadroesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ia': {
      id: '/app/ia'
      path: '/ia'
      fullPath: '/app/ia'
      preLoaderRoute: typeof AppIaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/conta': {
      id: '/app/conta'
      path: '/conta'
      fullPath: '/app/conta'
      preLoaderRoute: typeof AppContaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendario': {
      id: '/app/calendario'
      path: '/calendario'
      fullPath: '/app/calendario'
      preLoaderRoute: typeof AppCalendarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/banca': {
      id: '/app/banca'
      path: '/banca'
      fullPath: '/app/banca'
      preLoaderRoute: typeof AppBancaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assinatura': {
      id: '/app/assinatura'
      path: '/assinatura'
      fullPath: '/app/assinatura'
      preLoaderRoute: typeof AppAssinaturaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agentes': {
      id: '/app/agentes'
      path: '/agentes'
      fullPath: '/app/agentes'
      preLoaderRoute: typeof AppAgentesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/modules': {
      id: '/app/admin/modules'
      path: '/modules'
      fullPath: '/app/admin/modules'
      preLoaderRoute: typeof AppAdminModulesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/logs': {
      id: '/app/admin/logs'
      path: '/logs'
      fullPath: '/app/admin/logs'
      preLoaderRoute: typeof AppAdminLogsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/crm': {
      id: '/app/admin/crm'
      path: '/crm'
      fullPath: '/app/admin/crm'
      preLoaderRoute: typeof AppAdminCrmRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/broadcast': {
      id: '/app/admin/broadcast'
      path: '/broadcast'
      fullPath: '/app/admin/broadcast'
      preLoaderRoute: typeof AppAdminBroadcastRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminBroadcastRoute: typeof AppAdminBroadcastRoute
  AppAdminCrmRoute: typeof AppAdminCrmRoute
  AppAdminLogsRoute: typeof AppAdminLogsRoute
  AppAdminModulesRoute: typeof AppAdminModulesRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminBroadcastRoute: AppAdminBroadcastRoute,
  AppAdminCrmRoute: AppAdminCrmRoute,
  AppAdminLogsRoute: AppAdminLogsRoute,
  AppAdminModulesRoute: AppAdminModulesRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppAgentesRoute: typeof AppAgentesRoute
  AppAssinaturaRoute: typeof AppAssinaturaRoute
  AppBancaRoute: typeof AppBancaRoute
  AppCalendarioRoute: typeof AppCalendarioRoute
  AppContaRoute: typeof AppContaRoute
  AppIaRoute: typeof AppIaRoute
  AppPadroesRoute: typeof AppPadroesRoute
  AppPagamentosRoute: typeof AppPagamentosRoute
  AppPlanosRoute: typeof AppPlanosRoute
  AppValidadorRoute: typeof AppValidadorRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppAgentesRoute: AppAgentesRoute,
  AppAssinaturaRoute: AppAssinaturaRoute,
  AppBancaRoute: AppBancaRoute,
  AppCalendarioRoute: AppCalendarioRoute,
  AppContaRoute: AppContaRoute,
  AppIaRoute: AppIaRoute,
  AppPadroesRoute: AppPadroesRoute,
  AppPagamentosRoute: AppPagamentosRoute,
  AppPlanosRoute: AppPlanosRoute,
  AppValidadorRoute: AppValidadorRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DevSessionRoute: DevSessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
