/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppVozRouteImport } from './routes/app.voz'
import { Route as AppPlanosRouteImport } from './routes/app.planos'
import { Route as AppPagamentosRouteImport } from './routes/app.pagamentos'
import { Route as AppIaRouteImport } from './routes/app.ia'
import { Route as AppContaRouteImport } from './routes/app.conta'
import { Route as AppAssinaturaRouteImport } from './routes/app.assinatura'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppAdminUsersRouteImport } from './routes/app.admin.users'
import { Route as AppAdminModulesRouteImport } from './routes/app.admin.modules'
import { Route as AppAdminLogsRouteImport } from './routes/app.admin.logs'
import { Route as AppAdminBroadcastRouteImport } from './routes/app.admin.broadcast'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVozRoute = AppVozRouteImport.update({
  id: '/voz',
  path: '/voz',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanosRoute = AppPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AppRoute,
} as any)
const AppPagamentosRoute = AppPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AppRoute,
} as any)
const AppIaRoute = AppIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AppRoute,
} as any)
const AppContaRoute = AppContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AppRoute,
} as any)
const AppAssinaturaRoute = AppAssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminModulesRoute = AppAdminModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminLogsRoute = AppAdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminBroadcastRoute = AppAdminBroadcastRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/assinatura': typeof AppAssinaturaRoute
  '/app/conta': typeof AppContaRoute
  '/app/ia': typeof AppIaRoute
  '/app/pagamentos': typeof AppPagamentosRoute
  '/app/planos': typeof AppPlanosRoute
  '/app/voz': typeof AppVozRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/broadcast': typeof AppAdminBroadcastRoute
  '/app/admin/logs': typeof AppAdminLogsRoute
  '/app/admin/modules': typeof AppAdminModulesRoute
  '/app/admin/users': typeof AppAdminUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/assinatura': typeof AppAssinaturaRoute
  '/app/conta': typeof AppContaRoute
  '/app/ia': typeof AppIaRoute
  '/app/pagamentos': typeof AppPagamentosRoute
  '/app/planos': typeof AppPlanosRoute
  '/app/voz': typeof AppVozRoute
  '/app': typeof AppIndexRoute
  '/app/admin/broadcast': typeof AppAdminBroadcastRoute
  '/app/admin/logs': typeof AppAdminLogsRoute
  '/app/admin/modules': typeof AppAdminModulesRoute
  '/app/admin/users': typeof AppAdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/assinatura': typeof AppAssinaturaRoute
  '/app/conta': typeof AppContaRoute
  '/app/ia': typeof AppIaRoute
  '/app/pagamentos': typeof AppPagamentosRoute
  '/app/planos': typeof AppPlanosRoute
  '/app/voz': typeof AppVozRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/broadcast': typeof AppAdminBroadcastRoute
  '/app/admin/logs': typeof AppAdminLogsRoute
  '/app/admin/modules': typeof AppAdminModulesRoute
  '/app/admin/users': typeof AppAdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/admin'
    | '/app/assinatura'
    | '/app/conta'
    | '/app/ia'
    | '/app/pagamentos'
    | '/app/planos'
    | '/app/voz'
    | '/app/'
    | '/app/admin/broadcast'
    | '/app/admin/logs'
    | '/app/admin/modules'
    | '/app/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/admin'
    | '/app/assinatura'
    | '/app/conta'
    | '/app/ia'
    | '/app/pagamentos'
    | '/app/planos'
    | '/app/voz'
    | '/app'
    | '/app/admin/broadcast'
    | '/app/admin/logs'
    | '/app/admin/modules'
    | '/app/admin/users'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/admin'
    | '/app/assinatura'
    | '/app/conta'
    | '/app/ia'
    | '/app/pagamentos'
    | '/app/planos'
    | '/app/voz'
    | '/app/'
    | '/app/admin/broadcast'
    | '/app/admin/logs'
    | '/app/admin/modules'
    | '/app/admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/voz': {
      id: '/app/voz'
      path: '/voz'
      fullPath: '/app/voz'
      preLoaderRoute: typeof AppVozRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/planos': {
      id: '/app/planos'
      path: '/planos'
      fullPath: '/app/planos'
      preLoaderRoute: typeof AppPlanosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pagamentos': {
      id: '/app/pagamentos'
      path: '/pagamentos'
      fullPath: '/app/pagamentos'
      preLoaderRoute: typeof AppPagamentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ia': {
      id: '/app/ia'
      path: '/ia'
      fullPath: '/app/ia'
      preLoaderRoute: typeof AppIaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/conta': {
      id: '/app/conta'
      path: '/conta'
      fullPath: '/app/conta'
      preLoaderRoute: typeof AppContaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assinatura': {
      id: '/app/assinatura'
      path: '/assinatura'
      fullPath: '/app/assinatura'
      preLoaderRoute: typeof AppAssinaturaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/modules': {
      id: '/app/admin/modules'
      path: '/modules'
      fullPath: '/app/admin/modules'
      preLoaderRoute: typeof AppAdminModulesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/logs': {
      id: '/app/admin/logs'
      path: '/logs'
      fullPath: '/app/admin/logs'
      preLoaderRoute: typeof AppAdminLogsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/broadcast': {
      id: '/app/admin/broadcast'
      path: '/broadcast'
      fullPath: '/app/admin/broadcast'
      preLoaderRoute: typeof AppAdminBroadcastRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminBroadcastRoute: typeof AppAdminBroadcastRoute
  AppAdminLogsRoute: typeof AppAdminLogsRoute
  AppAdminModulesRoute: typeof AppAdminModulesRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminBroadcastRoute: AppAdminBroadcastRoute,
  AppAdminLogsRoute: AppAdminLogsRoute,
  AppAdminModulesRoute: AppAdminModulesRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppAssinaturaRoute: typeof AppAssinaturaRoute
  AppContaRoute: typeof AppContaRoute
  AppIaRoute: typeof AppIaRoute
  AppPagamentosRoute: typeof AppPagamentosRoute
  AppPlanosRoute: typeof AppPlanosRoute
  AppVozRoute: typeof AppVozRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppAssinaturaRoute: AppAssinaturaRoute,
  AppContaRoute: AppContaRoute,
  AppIaRoute: AppIaRoute,
  AppPagamentosRoute: AppPagamentosRoute,
  AppPlanosRoute: AppPlanosRoute,
  AppVozRoute: AppVozRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
