/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppVozRouteImport } from './routes/app.voz'
import { Route as AppPlanosRouteImport } from './routes/app.planos'
import { Route as AppIaRouteImport } from './routes/app.ia'
import { Route as AppContaRouteImport } from './routes/app.conta'
import { Route as AppAdminRouteImport } from './routes/app.admin'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVozRoute = AppVozRouteImport.update({
  id: '/voz',
  path: '/voz',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanosRoute = AppPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AppRoute,
} as any)
const AppIaRoute = AppIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AppRoute,
} as any)
const AppContaRoute = AppContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/admin': typeof AppAdminRoute
  '/app/conta': typeof AppContaRoute
  '/app/ia': typeof AppIaRoute
  '/app/planos': typeof AppPlanosRoute
  '/app/voz': typeof AppVozRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/admin': typeof AppAdminRoute
  '/app/conta': typeof AppContaRoute
  '/app/ia': typeof AppIaRoute
  '/app/planos': typeof AppPlanosRoute
  '/app/voz': typeof AppVozRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/admin': typeof AppAdminRoute
  '/app/conta': typeof AppContaRoute
  '/app/ia': typeof AppIaRoute
  '/app/planos': typeof AppPlanosRoute
  '/app/voz': typeof AppVozRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/admin'
    | '/app/conta'
    | '/app/ia'
    | '/app/planos'
    | '/app/voz'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/admin'
    | '/app/conta'
    | '/app/ia'
    | '/app/planos'
    | '/app/voz'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/admin'
    | '/app/conta'
    | '/app/ia'
    | '/app/planos'
    | '/app/voz'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/voz': {
      id: '/app/voz'
      path: '/voz'
      fullPath: '/app/voz'
      preLoaderRoute: typeof AppVozRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/planos': {
      id: '/app/planos'
      path: '/planos'
      fullPath: '/app/planos'
      preLoaderRoute: typeof AppPlanosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ia': {
      id: '/app/ia'
      path: '/ia'
      fullPath: '/app/ia'
      preLoaderRoute: typeof AppIaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/conta': {
      id: '/app/conta'
      path: '/conta'
      fullPath: '/app/conta'
      preLoaderRoute: typeof AppContaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppContaRoute: typeof AppContaRoute
  AppIaRoute: typeof AppIaRoute
  AppPlanosRoute: typeof AppPlanosRoute
  AppVozRoute: typeof AppVozRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppContaRoute: AppContaRoute,
  AppIaRoute: AppIaRoute,
  AppPlanosRoute: AppPlanosRoute,
  AppVozRoute: AppVozRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
