// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function firstEnvValue(...values: Array<unknown>) {
  return values.find((value): value is string => typeof value === 'string' && value.trim().length > 0)?.trim();
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const runtimeEnv = typeof process !== 'undefined' ? process.env : {};
  const SUPABASE_URL = firstEnvValue(
    import.meta.env.VITE_SUPABASE_URL,
    runtimeEnv.SNIPER_SUPABASE_URL,
    runtimeEnv.SUPABASE_URL,
  );
  const SUPABASE_PUBLISHABLE_KEY = firstEnvValue(
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY,
    import.meta.env.VITE_SUPABASE_ANON_KEY,
    runtimeEnv.SNIPER_SUPABASE_PUBLISHABLE_KEY,
    runtimeEnv.SNIPER_SUPABASE_ANON_KEY,
    runtimeEnv.SUPABASE_PUBLISHABLE_KEY,
    runtimeEnv.SUPABASE_ANON_KEY,
  );

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY or SUPABASE_ANON_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

